import type { Config } from 'tailwindcss';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#060e20',
        'primary-fixed-dim': '#ffb95f',
        'inverse-surface': '#dae2fd',
        'surface-container-low': '#131b2e',
        tertiary: '#54ddfc',
        'primary-container': '#f59e0b',
        'outline-variant': '#534434',
        'on-primary-fixed': '#2a1700',
        'secondary-container': '#571bc1',
        'surface-dim': '#0b1326',
        'tertiary-fixed-dim': '#4cd7f6',
        'inverse-primary': '#855300',
        'on-primary': '#472a00',
        error: '#ffb4ab',
        'tertiary-fixed': '#acedff',
        'on-secondary-fixed-variant': '#5516be',
        'primary-fixed': '#ffddb8',
        'on-error': '#690005',
        'surface-tint': '#ffb95f',
        'secondary-fixed': '#e9ddff',
        outline: '#a08e7a',
        'surface-bright': '#31394d',
        'on-secondary-fixed': '#23005c',
        'on-secondary-container': '#c4abff',
        'tertiary-container': '#29c1df',
        'error-container': '#93000a',
        background: '#0b1326',
        'on-error-container': '#ffdad6',
        'surface-container-highest': '#2d3449',
        'on-surface-variant': '#d8c3ad',
        'on-tertiary': '#003640',
        secondary: '#d0bcff',
        'surface-variant': '#2d3449',
        'on-tertiary-fixed-variant': '#004e5c',
        'secondary-fixed-dim': '#d0bcff',
        'on-tertiary-fixed': '#001f26',
        'on-surface': '#dae2fd',
        'surface-container-high': '#222a3d',
        'on-primary-container': '#613b00',
        'surface-container': '#171f33',
        'on-background': '#dae2fd',
        'on-primary-fixed-variant': '#653e00',
        primary: '#ffc174',
        'inverse-on-surface': '#283044',
        surface: '#0b1326',
        'on-tertiary-container': '#004b58',
        'on-secondary': '#3c0091',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
        'margin-mobile': '1rem',
        margin: '2rem',
        'space-lg': '1.5rem',
        'gutter-mobile': '1rem',
        gutter: '1.5rem',
      },
      fontFamily: {
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'headline-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'code-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
} satisfies Config;
